<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TaskMessage.proto

namespace AnasEqal\LaravelAsynq\Protobuf\GPBMetadata;

class TaskMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ó
TaskMessage.proto"…
TaskMessage
type (	
payload (

id (	
queue (	
retry (
retried (
	error_msg (	
last_failed_at (
timeout (
deadline	 (

unique_key
 (	
	group_key (	
	retention (
completed_at (BNÊAnasEqal\\LaravelAsynq\\Protobufâ*AnasEqal\\LaravelAsynq\\Protobuf\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

