<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TaskMessage.proto

namespace AnasEqal\LaravelAsynq\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * TaskMessage is the internal representation of a task with additional metadata fields.
 *
 * Generated from protobuf message <code>TaskMessage</code>
 */
class TaskMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string type = 1;</code>
     */
    protected $type = '';
    /**
     * Generated from protobuf field <code>bytes payload = 2;</code>
     */
    protected $payload = '';
    /**
     * Generated from protobuf field <code>string id = 3;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string queue = 4;</code>
     */
    protected $queue = '';
    /**
     * Generated from protobuf field <code>int32 retry = 5;</code>
     */
    protected $retry = 0;
    /**
     * Generated from protobuf field <code>int32 retried = 6;</code>
     */
    protected $retried = 0;
    /**
     * Generated from protobuf field <code>string error_msg = 7;</code>
     */
    protected $error_msg = '';
    /**
     * Generated from protobuf field <code>int64 last_failed_at = 11;</code>
     */
    protected $last_failed_at = 0;
    /**
     * Generated from protobuf field <code>int64 timeout = 8;</code>
     */
    protected $timeout = 0;
    /**
     * Generated from protobuf field <code>int64 deadline = 9;</code>
     */
    protected $deadline = 0;
    /**
     * Generated from protobuf field <code>string unique_key = 10;</code>
     */
    protected $unique_key = '';
    /**
     * Generated from protobuf field <code>string group_key = 14;</code>
     */
    protected $group_key = '';
    /**
     * Generated from protobuf field <code>int64 retention = 12;</code>
     */
    protected $retention = 0;
    /**
     * Generated from protobuf field <code>int64 completed_at = 13;</code>
     */
    protected $completed_at = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $type
     *     @type string $payload
     *     @type string $id
     *     @type string $queue
     *     @type int $retry
     *     @type int $retried
     *     @type string $error_msg
     *     @type int|string $last_failed_at
     *     @type int|string $timeout
     *     @type int|string $deadline
     *     @type string $unique_key
     *     @type string $group_key
     *     @type int|string $retention
     *     @type int|string $completed_at
     * }
     */
    public function __construct($data = NULL) {
        \AnasEqal\LaravelAsynq\Protobuf\GPBMetadata\TaskMessage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string type = 1;</code>
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>string type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes payload = 2;</code>
     * @return string
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * Generated from protobuf field <code>bytes payload = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkString($var, False);
        $this->payload = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string id = 3;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string queue = 4;</code>
     * @return string
     */
    public function getQueue()
    {
        return $this->queue;
    }

    /**
     * Generated from protobuf field <code>string queue = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setQueue($var)
    {
        GPBUtil::checkString($var, True);
        $this->queue = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 retry = 5;</code>
     * @return int
     */
    public function getRetry()
    {
        return $this->retry;
    }

    /**
     * Generated from protobuf field <code>int32 retry = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setRetry($var)
    {
        GPBUtil::checkInt32($var);
        $this->retry = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 retried = 6;</code>
     * @return int
     */
    public function getRetried()
    {
        return $this->retried;
    }

    /**
     * Generated from protobuf field <code>int32 retried = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setRetried($var)
    {
        GPBUtil::checkInt32($var);
        $this->retried = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string error_msg = 7;</code>
     * @return string
     */
    public function getErrorMsg()
    {
        return $this->error_msg;
    }

    /**
     * Generated from protobuf field <code>string error_msg = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->error_msg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 last_failed_at = 11;</code>
     * @return int|string
     */
    public function getLastFailedAt()
    {
        return $this->last_failed_at;
    }

    /**
     * Generated from protobuf field <code>int64 last_failed_at = 11;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastFailedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->last_failed_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 timeout = 8;</code>
     * @return int|string
     */
    public function getTimeout()
    {
        return $this->timeout;
    }

    /**
     * Generated from protobuf field <code>int64 timeout = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimeout($var)
    {
        GPBUtil::checkInt64($var);
        $this->timeout = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 deadline = 9;</code>
     * @return int|string
     */
    public function getDeadline()
    {
        return $this->deadline;
    }

    /**
     * Generated from protobuf field <code>int64 deadline = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDeadline($var)
    {
        GPBUtil::checkInt64($var);
        $this->deadline = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string unique_key = 10;</code>
     * @return string
     */
    public function getUniqueKey()
    {
        return $this->unique_key;
    }

    /**
     * Generated from protobuf field <code>string unique_key = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setUniqueKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->unique_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string group_key = 14;</code>
     * @return string
     */
    public function getGroupKey()
    {
        return $this->group_key;
    }

    /**
     * Generated from protobuf field <code>string group_key = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 retention = 12;</code>
     * @return int|string
     */
    public function getRetention()
    {
        return $this->retention;
    }

    /**
     * Generated from protobuf field <code>int64 retention = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRetention($var)
    {
        GPBUtil::checkInt64($var);
        $this->retention = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 completed_at = 13;</code>
     * @return int|string
     */
    public function getCompletedAt()
    {
        return $this->completed_at;
    }

    /**
     * Generated from protobuf field <code>int64 completed_at = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCompletedAt($var)
    {
        GPBUtil::checkInt64($var);
        $this->completed_at = $var;

        return $this;
    }

}

